### ISSUE TITLE
OCDP Broker创建Yarn队列时需要考虑集群资源总量

### ISSUE THREAD

**Issue by baikai** [OCManager/OCDP_ServiceBroker#13]
OCDP Broker创建Yarn队列时需要考虑集群资源状况，如果当前集群资源不足则应该返回创建失败。
当前行为是broker在集群资源不足的情况下，依然会调用ambari view的rest去创建队列，然后ambari view 创建队列失败。

**Comment by qianguo1** [comment]
经验证,目前OCDP service broker会对申请资源与集群空闲资源进行比较,如果空闲资源不足,则会抛出异常,不会再调用ambari view的rest去创建队列.所以此bug不存在.
