### ISSUE TITLE
ETCD record not completely removed 

### ISSUE THREAD

**Issue by Ethan19881224** [OCManager/OCDP_ServiceBroker#21]
'tenantName' was added to credentials but not stored in ETCD when provision a instance. This leads to failure of deprovision action when programs needs to delete ETCD record which needs 'tenantName' in path.

**Comment by baikai** [comment]
Thanks Ethan, I will fix it soon.

**Comment by baikai** [comment]
Fix by commit 3a4c2686987a2e7b85fdc9c3dbf4c494e7125e4d
