### ISSUE TITLE
CommonService 向TenantPolicy追加Resource时没有对返回结果做处理

### ISSUE THREAD

**Issue by Ethan19881224** [OCManager/OCDP_ServiceBroker#23]
CommonService 向TenantPolicy追加Resource时没有对返回结果做处理。是否应该对返回布尔值做相应处理，如果调用失败如何处理合适，抛异常？

**Comment by baikai** [comment]
Fix by commit ac60a7ada192dbfc57249f2504e0730654ce0505.
