### ISSUE TITLE
支持Hadoop组件的HA

### ISSUE THREAD

**Issue by baikai** [OCManager/OCDP_ServiceBroker#3]
目前，ocdp service broker对hadoop组件的调用没有考虑组件的HA，主要包括:
- HDFS HA
- Yarn HA
- Hive HA (?)

**Comment by qianguo1** [comment]
HDFS HA: 在代码中加入hdfs nameservices的相关配置,就可以使用nameservices代替namenode hostname来访问HDFS了.
YARN HA: 当主备resource manager同时运行的时候,调用standby RM的rest api,会自动重定向到active RM上,返回正确的结果.当standby RM挂掉的时候,如果调用standby RM就无法连接. 因此在调用RM rest api时,依次尝试两个RM hostname,如果两个都不能成功连接,才返回连接失败的异常.
HIVE HA: HIVE没有HA机制,生产环境一般是配多个hive server2供不同应用使用. 中信的环境目前只有一个hive server2,所以暂时不考虑对HIVE HA的支持.

**Comment by baikai** [comment]
Fix by commit cd6c003813135e9f49ffdbb67c8b44fa18de61ff.
