### ISSUE TITLE
重构Spark/MapReduce服务实现

### ISSUE THREAD

**Issue by baikai** [OCManager/OCDP_ServiceBroker#40]
重构Spark/MapReduce服务实现：
- 目前两个服务的代码高度相似，后期可以考虑合并成一个服务实现，但是仍然对外暴露为两个服务
- Spark/MapReduce对HDFS目录的权限(/user/<username>)，最好同一个用户能只有一个ranger policy去处理

**Comment by qianguo1** [comment]
把SparkAdminService和MapReduceAdminService合成一个YarnAdminService
