### ISSUE TITLE
解决Yarn Queue的Capacity数值问题

### ISSUE THREAD

**Issue by baikai** [OCManager/OCDP_ServiceBroker#6]
问题：当前Broker所创建的yarn queue的capacity数值过于精确(小数点后15位)，而ambari的yarn queue view只支持整数位的queue capacity(即支持2%，不支持2.1%)，导致当queue数目较多时候ambari的yarn queue view计算出错误的总capacity，再以错误的总capacity去刷新capacity-scheduler从而导致yarn挂掉。
解决：对计算出的yarn queue的capacity数值进行截断，只保留整数位。

**Comment by qianguo1** [comment]
在现场的环境中打一个ambari server的patch,可以支持有两位小数的queue capacity(如2.02%).
service broker中把计算出的capacity处理为保留两位小时即可.

**Comment by baikai** [comment]
Fix by commit cd6c003813135e9f49ffdbb67c8b44fa18de61ff.
